[package]
name = "wasm-sudoku"
version = "0.1.0"
authors = ["bryantdeters <bryant.j.deters@centene.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
itertools = "0.8"
